### ISSUE TITLE
There was an error processing your request when me add new custom sort order on product list 

### ISSUE THREAD

**Issue by tungoanh** [ctasca/magento-elasticsearch-module#23]
Hi,
I has added new custom sort order on product list.
In catalogsearch page error when i choose 'new custom sort order' on list product.
If i choose default sort order have not error.

can you help me for this error ?

Thank you,

Ngo

**Comment by ctasca** [comment]
Can you provide log of the error/exception? thanks

**Comment by tungoanh** [comment]
https://docs.google.com/a/sutunam.com/file/d/0B_Kw7NtRHTbBem9IR2VOcl9LVDA/edit?usp=drivesdk


error/exception: 

pls help me: 
Il y a eu une erreur lors du traitement de votre demande

SELECT 1 AS `status`, `e`.`entity_id`, `e`.`type_id`, `e`.`attribute_set_id`, `e`.`name`, `e`.`description`, `e`.`short_description`, `e`.`price`, `e`.`special_price`, `e`.`special_from_date`, `e`.`special_to_date`, `e`.`small_image`, `e`.`thumbnail`, `e`.`news_from_date`, `e`.`news_to_date`, `e`.`url_key`, `e`.`required_options`, `e`.`image_label`, `e`.`small_image_label`, `e`.`thumbnail_label`, `e`.`msrp_enabled`, `e`.`msrp_display_actual_price_type`, `e`.`msrp`, `e`.`tax_class_id`, `e`.`price_type`, `e`.`weight_type`, `e`.`price_view`, `e`.`shipment_type`, `e`.`links_purchased_separately`, `e`.`links_exist`, `e`.`pictos`, `e`.`giftwrap`, `e`.`ean`, `e`.`gift_amount`, `e`.`show_gift_amount_desc`, `e`.`gift_amount_desc`, `e`.`giftcard_description`, `e`.`color_of_banner`, `e`.`color_of_banner_value`, `e`.`text_on_banner`, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price`, `cat_index`.`position` AS `cat_index_position`, `stock_status`.`stock_status` AS `salable` FROM `catalog_product_flat_1` AS `e`
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0
 INNER JOIN `catalog_category_product_index` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id='1' AND cat_index.visibility IN(3, 4) AND cat_index.category_id='2'
 LEFT JOIN `cataloginventory_stock_status` AS `stock_status` ON e.entity_id = stock_status.product_id AND stock_status.website_id=1 WHERE (e.entity_id IN ()) ORDER BY `salable` desc, `e`.`sutu_position` desc, `e`.`name` asc, `e`.`news_to_date` desc, `e`.`name` asc



                Trace:
                #0 /home/hyperparapharmacie.dev3.sutunam.com/public_html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/hyperparapharmacie.dev3.sutunam.com/public_html/lib/Zend/Db/Statement.php(300): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /home/hyperparapharmacie.dev3.sutunam.com/public_html/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#3 /home/hyperparapharmacie.dev3.sutunam.com/public_html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT 1 AS `st...', Array)
#4 /home/hyperparapharmacie.dev3.sutunam.com/public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php(419): Zend_Db_Adapter_Pdo_Abstract->query('SELECT 1 AS `st...', Array)
#5 /home/hyperparapharmacie.dev3.sutunam.com/public_html/lib/Zend/Db/Adapter/Abstract.php(734): Varien_Db_Adapter_Pdo_Mysql->query('SELECT 1 AS `st...', Array)
#6 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/local/Varien/Data/Collection/Db.php(742): Zend_Db_Adapter_Abstract->fetchAll('SELECT 1 AS `st...', Array)
#7 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(1047): Varien_Data_Collection_Db->_fetchAll('SELECT 1 AS `st...')
#8 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(871): Mage_Eav_Model_Entity_Collection_Abstract->_loadEntities(false, false)
#9 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Review/Model/Observer.php(78): Mage_Eav_Model_Entity_Collection_Abstract->load()
#10 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Model/App.php(1338): Mage_Review_Model_Observer->catalogBlockProductCollectionBeforeToHtml(Object(Varien_Event_Observer))
#11 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Model/App.php(1311): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Review_Model_Observer), 'catalogBlockPro...', Object(Varien_Event_Observer))
#12 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/Mage.php(447): Mage_Core_Model_App->dispatchEvent('catalog_block_p...', Array)
#13 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Catalog/Block/Product/List.php(163): Mage::dispatchEvent('catalog_block_p...', Array)
#14 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(862): Mage_Catalog_Block_Product_List->_beforeToHtml()
#15 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(582): Mage_Core_Block_Abstract->toHtml()
#16 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(526): Mage_Core_Block_Abstract->_getChildHtml('search_result_l...', true)
#17 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/CatalogSearch/Block/Result.php(161): Mage_Core_Block_Abstract->getChildHtml('search_result_l...')
#18 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/design/frontend/ecommerce/default/template/catalogsearch/result.phtml(42): Mage_CatalogSearch_Block_Result->getProductListHtml()
#19 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/hyperpara...')
#20 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/ecomme...')
#21 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#22 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(863): Mage_Core_Block_Template->_toHtml()
#23 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#24 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(863): Mage_Core_Block_Text_List->_toHtml()
#25 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(582): Mage_Core_Block_Abstract->toHtml()
#26 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(526): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#27 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/design/frontend/ecommerce/default/template/page/2columns-left.phtml(51): Mage_Core_Block_Abstract->getChildHtml('content')
#28 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Block/Template.php(241): include('/home/hyperpara...')
#29 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/ecomme...')
#30 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#31 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Block/Abstract.php(863): Mage_Core_Block_Template->_toHtml()
#32 /home/hyperparapharmacie.dev3.sutunam.com/public_html/var/cache/ew/files/Mage/Core/Model/Layout/a98f181a3dc22489d2af4466edf817fa.php(555): Mage_Core_Block_Abstract->toHtml()
#33 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_LayoutOverriddenClass->getOutput()
#34 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/CatalogSearch/controllers/ResultController.php(80): Mage_Core_Controller_Varien_Action->renderLayout()
#35 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(419): Mage_CatalogSearch_ResultController->indexAction()
#36 /home/hyperparapharmacie.dev3.sutunam.com/public_html/var/cache/ew/files/Mage/Core/Controller/Varien/Router/Standard/088bf81233af8a733a03eb4d9a3bcae0.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#37 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_StandardOverriddenClass->match(Object(Mage_Core_Controller_Request_Http))
#38 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#39 /home/hyperparapharmacie.dev3.sutunam.com/public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#40 /home/hyperparapharmacie.dev3.sutunam.com/public_html/index.php(104): Mage::run('', 'store')
#41 {main}
